stages:
  # - setup
  # - portal-setup
  - test-setup
  # - pre-test-setup
  - cypress-test
  # - portal-cleanup
  # - cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - CypressE2E/node_modules

# Cluster Connect:
#   image: jonsy13/runner:latest
#   stage: setup
#   tags:
#     - litmus-portal-2
#   script:
#     - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
#     - ./build/gitlab/stages/1-gke-setup/cluster-setup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}

# Portal-Setup:
#   image: jonsy13/runner:latest
#   when: always
#   stage: portal-setup
#   tags: 
#     - litmus-portal-2
#   script:
#     - chmod 755 ./install.sh
#     - ./install.sh
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#     reports:
#       dotenv: Portal-Setup.env
#   cache: {}

Cypress-Setup:
  when: always
  stage: test-setup
  image: cypress/base:10
  tags:
    - litmus-portal-2
  script:
    - cd CypressE2E && npm ci

# PreTest-Setup:
#   when: always
#   stage: pre-test-setup
#   image:
#     name: cypress/base:10
#   tags:
#     - litmus-portal-2
#   script:
#     - echo ${FRONTEND_IP}
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Basic_Setup
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots
#   dependencies:
#     - Portal-Setup

# .cypress-e2e:
#   when: always
#   stage: cypress-test
#   image:
#     name: cypress/base:10
#   tags:
#     - litmus-portal-2
#   script:
#     - echo ${FRONTEND_IP}
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots
#   dependencies:
#     - Portal-Setup

# cypress-e2e:
#   when: always
#   stage: pre-test-setup
#   image:
#     name: cypress/included:5.2.0
#     entrypoint: [""]
#   tags:
#     - litmus-portal-2
#   script:
#     - echo ${FRONTEND_IP}
#     - CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ cypress run --project ./CypressE2E --spec 'CypressE2E/cypress/integration/Basic_Setup/**/*.spec.js'
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots/**/*.png
#   dependencies:
#     - Portal-Setup

# cypress-e2e-2:
#   when: always
#   stage: cypress-test
#   image:
#     name: cypress/base:10
#   tags:
#     - litmus-portal-2
#   script:
#     - echo ${FRONTEND_IP}
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Routes_Test
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots
#   dependencies:
#     - Portal-Setup


# routes-check:
#   extends: .cypress-e2e
#   after_script:
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Routes_Test

# create-workflow:
#   extends: .cypress-e2e
#   after_script: 
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Create_Test

# community-data:
#   extends: .cypress-e2e
#   after_script: 
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Community_Test

# account-settings:
#   extends: .cypress-e2e
#   after_script: 
#     - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run Account_Settings

# all jobs that actually run tests can use the same definition
# .job_template:
#   when: always
#   image:
#     name: cypress/included:5.2.0
#     # cypress/included images have entrypoint set to "cypress"
#     # which conflicts with GitLab CI wrapper shell script
#     entrypoint: [""]
#   stage: cypress-test
#   tags:
#     - litmus-portal-2
#   artifacts:
#     when: always
#     paths:
#       - CypressE2E/cypress/screenshots/**/*.png
#     expire_in: 1 day
#   dependencies:
#     - Portal-Setup

# actual job definitions
# all steps are the same, they come from the template above
# CommunityData-Check:
#   extends: .job_template
#   script: CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ cypress run --project ./CypressE2E --spec 'CypressE2E/cypress/integration/Parallel_Tests/Community/*.spec.js'

# Routes-Check:
#   extends: .job_template
#   script: CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ cypress run --project ./CypressE2E --spec 'CypressE2E/cypress/integration/Parallel_Tests/Routes/*.spec.js'

# CreateWorkflow-Check:
#   extends: .job_template
#   script: CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ cypress run --project ./CypressE2E --spec 'CypressE2E/cypress/integration/Parallel_Tests/Create_Workflow/*.spec.js'

# AccountSettings-Check:
#   extends: .job_template
#   script: CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ cypress run --project ./CypressE2E --spec 'CypressE2E/cypress/integration/Parallel_Tests/Account_Settings/*.spec.js'

# portal-cleanup:
#   when: always
#   image: jonsy13/runner:latest
#   stage: portal-cleanup
#   tags: 
#     - litmus-portal-2
#   script:
#     - chmod 755 ./uninstall.sh
#     - ./uninstall.sh
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}
    
# Cluster Disconnect:
#   when: always
#   image: jonsy13/runner:latest
#   stage: cleanup
#   tags:
#     - litmus-portal-2
#   script: 
#     - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
#     - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}

tests:
  stage: cypress-test
  image: cypress/base:10
  parallel: 4
  script: 
    - cd CypressE2E/ && npm run Community_Test