stages:
  - setup
  - portal-setup
  - test-setup
  - pre-test-setup
  - cypress-test
  - portal-cleanup
  - cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &global_cache
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - CypressE2E/node_modules

Cluster Connect:
  image: jonsy13/runner:latest
  stage: setup
  tags:
    - litmus-portal-2
  script:
    - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
    - ./build/gitlab/stages/1-gke-setup/cluster-setup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}

Portal-Setup:
  image: jonsy13/runner:latest
  when: always
  stage: portal-setup
  tags: 
    - litmus-portal-2
  script:
    - chmod 755 ./install.sh
    - ./install.sh
  artifacts:
    when: always
    paths:
      - .kube/
    reports:
      dotenv: Portal-Setup.env
  cache: {}

Cypress-Setup:
  when: always
  stage: test-setup
  image: cypress/base:10
  # tags:
  #   - litmus-portal-2
  script:
    - make cypress-setup

PreTest-Setup:
  when: always
  stage: pre-test-setup
  image:
    name: cypress/base:10
  # tags:
  #   - litmus-portal-2
  script:
    - echo ${FRONTEND_IP}
    - make pre-test-setup
  artifacts:
    when: always
    paths:
      - CypressE2E/cypress/screenshots
  dependencies:
    - Portal-Setup
  cache:
    <<: *global_cache
    policy: pull

.cypress-e2e:
  when: always
  stage: cypress-test
  image:
    name: cypress/base:10
  # tags:
  #   - litmus-portal-2
  before_script:
    - echo ${FRONTEND_IP}
  artifacts:
    when: always
    paths:
      - CypressE2E/cypress/screenshots
  dependencies:
    - Portal-Setup
  cache:
    <<: *global_cache
    policy: pull

routesCheck_Tests:
  extends: .cypress-e2e
  script:
    - make routes-check

createWorkflow_Tests:
  extends: .cypress-e2e
  script: 
    - cd CypressE2E && CYPRESS_BASE_URL=http://${FRONTEND_IP}:9091/ npm run CreateWorkflow_Tests

communityData_Tests:
  extends: .cypress-e2e
  script: 
    - make community-page-check

accountSettings_Tests:
  extends: .cypress-e2e
  script: 
    - make account-settings-check

browseWorkflow_Tests:
  extends: .cypress-e2e
  script: 
    - make browse-workflow-check

portal-cleanup:
  when: always
  image: jonsy13/runner:latest
  stage: portal-cleanup
  tags: 
    - litmus-portal-2
  script:
    - chmod 755 ./uninstall.sh
    - ./uninstall.sh
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}
    
Cluster Disconnect:
  when: always
  image: jonsy13/runner:latest
  stage: cleanup
  tags:
    - litmus-portal-2
  script: 
    - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
    - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
  artifacts:
    when: always
    paths:
      - .kube/
  cache: {}
